name: 'Validate Semantic Version'
description: 'Checks if the provided version follows Semantic Versioning'
inputs:
  version:
    description: 'Version to validate'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Validate Semantic Version
      shell: bash
      run: ${{ github.action_path }}/validate-semver.sh ${{ inputs.version }}
