name: Manual workflow 2

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string
      is-set-farewell-message:
        description: 'Set farewell message'
        required: false
        type: boolean

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"

  farewell:
    runs-on: ubuntu-latest

    steps:
    - name: Send Farewell
      if: ${{ inputs.is-set-farewell-message }}
      run: echo "Goodbye ${{ inputs.name }}"
