name: Validation Finished

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  message:
    runs-on: ubuntu-latest

    steps:
      - name: Print Tag
        run: echo "The tag is ${{ inputs.tag }}"
